import Component from "@egjs/component";
import { FlickingOptions, Direction, EventType, FlickingPanel, FlickingStatus, Plugin, ElementLike, DestroyOption } from "./types";
declare class Flicking extends Component {
    static VERSION: string;
    static DIRECTION: Direction;
    static EVENTS: EventType;
    options: FlickingOptions;
    private wrapper;
    private viewport;
    private eventContext;
    constructor(element: string | HTMLElement, options?: Partial<FlickingOptions>);
    prev(duration?: number): this;
    next(duration?: number): this;
    moveTo(index: number, duration?: number): this;
    getIndex(): number;
    getElement(): HTMLElement;
    getCurrentPanel(): FlickingPanel | null;
    getPanel(index: number): FlickingPanel | null;
    getAllPanels(includeClone?: boolean): FlickingPanel[];
    getVisiblePanels(): FlickingPanel[];
    getPanelCount(): number;
    getCloneCount(): number;
    getLastIndex(): number;
    setLastIndex(index: number): this;
    isPlaying(): boolean;
    enableInput(): this;
    disableInput(): this;
    getStatus(): FlickingStatus;
    setStatus(status: FlickingStatus): void;
    addPlugins(plugins: Plugin | Plugin[]): this;
    removePlugins(plugins: Plugin | Plugin[]): this;
    destroy(option?: Partial<DestroyOption>): void;
    resize: () => this;
    prepend(element: ElementLike | ElementLike[]): FlickingPanel[];
    append(element: ElementLike | ElementLike[]): FlickingPanel[];
    replace(index: number, element: ElementLike | ElementLike[]): FlickingPanel[];
    remove(index: number, deleteCount?: number): FlickingPanel[];
    sync(diffInfo: {
        list: HTMLElement[];
        maintained: number[][];
        added: number[];
        changed: number[][];
        removed: number[];
    }): this;
    private listenInput();
    private listenResize();
    private triggerEvent;
    private moveCamera;
}
export default Flicking;
