/*
 * Copyright (c) 2015 NAVER Corp.
 * egjs projects are licensed under the MIT license
 */
/* eslint-disable @typescript-eslint/consistent-type-definitions */
import { OnChange, OnFinish, OnHold, OnRelease } from "@egjs/axes";

import Panel from "~/core/Panel";
import { DIRECTION } from "~/const/external";
import { ValueOf } from "~/type/internal";

export type ReadyEvent = void;

export type ResizeEvent = {
  width: number;
  height: number;
  prev: {
    width: number;
    height: number;
  };
  sizeChanged: boolean;
  element: HTMLElement;
};

/**
 * @typedef
 * @type object
 * @memberof eg.Flicking
 * @property {string} type Name of the event.<ko>이벤트명</ko>
 * @property {number} index Index number of the current panel.<ko>현재 패널의 인덱스 번호.</ko>
 * @property {eg.Flicking.FlickingPanel|null} panel Current panel.<ko> 현재 패널.</ko>
 * @property {number} progress Absolute progress of how much it proceed from first panel. 0 at first panel, and 1 at last panel.<ko>첫 번째 패널로부터 얼마만큼 진행했는지를 나타내는 진행도. 첫번째 패널에서 0, 마지막 패널에서 1의 값을 갖는다.</ko>
 * @property {boolean} isTrusted `true` when the event was generated by a user action("mouse" or "touch") otherwise `false`.<ko>사용자 액션("mouse" 또는 "touch")에 의해 이벤트가 생성된 경우 `true`. 그 외는 `false`.</ko>
 * @property {boolean} holding Whether the user is inputting through the input device. (Whether it is 'mousedown' for a mouse device or 'touchmove' for a touch device.)<ko>사용자가 입력 장치를 통해 입력중인지 여부. (마우스 장치라면 'mousedown' 여부, 터치 장치라면 'touchmove' 여부)</ko>
 * @property {function} stop Cancel the default action, and prevents every events after it.<br>Not effective with events postfixed with `-End`<ko>이벤트의 기본동작을 취소하고, 해당 이벤트 뒤에 발생할 이벤트들을 전부 발생하지 않도록 한다.<br>`-End`가 접미사로 붙은 이벤트에서는 유효한 동작을 하지 않는다.</ko>
 * @property {"PREV" | "NEXT" | null} direction Direction of the panel movement. `null` if not moved at all.<ko>패널 이동 방향. 아직 움직이지 않았을 경우 `null`이다.</ko>
 * @property {object | undefined} axesEvent Original event emitted from {@link https://naver.github.io/egjs-axes/release/latest/doc/ Axes} instance.<ko>내부의 {@link https://naver.github.io/egjs-axes/release/latest/doc Axes} 인스턴스로부터 발생된 원본 이벤트.</ko>
 * @property {eg.Flicking} currentTarget Flicking instance that triggered event.<ko>이벤트를 발생시킨 Flicking의 인스턴스</ko>
 */
export type HoldStartEvent = {
  axesEvent: OnHold;
};

export type HoldEndEvent = {
  axesEvent: OnRelease;
};

export type MoveStartEvent = {
  isTrusted: boolean;
  holding: boolean;
  direction: ValueOf<typeof DIRECTION>;
  axesEvent: OnChange;
};

export type MoveEvent = {
  isTrusted: boolean;
  holding: boolean;
  direction: ValueOf<typeof DIRECTION>;
  axesEvent: OnChange;
};

export type MoveEndEvent = {
  isTrusted: boolean;
  direction: ValueOf<typeof DIRECTION>;
  axesEvent: OnFinish;
};

export type ChangeEvent = {
  index: number;
  panel: Panel;
  isTrusted: boolean;
  direction: ValueOf<typeof DIRECTION>;
  axesEvent?: OnRelease;
};

export type RestoreEvent = {
  index: number;
  panel: Panel;
  isTrusted: boolean;
  direction: ValueOf<typeof DIRECTION>;
  axesEvent?: OnRelease;
};

export type SelectEvent = {
  index: number;
  panel: Panel;
  direction: ValueOf<typeof DIRECTION> | null;
};

export type NeedPanelEvent = {
  direction: ValueOf<typeof DIRECTION>;
};

export type VisibleChangeEvent = {
  added: Panel[];
  removed: Panel[];
  panels: Panel[];
};
