name: Run tests
on: [push, pull_request]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          # 최신 노드 버전 사용
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: install
        run: pnpm install
      - name: install browsers
        run: pnpm --filter @test/unit exec playwright install --with-deps chromium
      - name: run unit test
        run: pnpm --filter @test/unit run coverage
      - name: send coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: unit
          base-path: ./packages/test-flicking/unit
          path-to-lcov: ./packages/test-flicking/unit/coverage/lcov.info
          parallel: true
  plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          # 최신 노드 버전 사용
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: install
        run: pnpm install
      - name: run plugins test
        run: pnpm test:plugins
  cfc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          # 최신 노드 버전 사용
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: install
        run: pnpm install
      - name: run cfc test
        run: pnpm test:cfc
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: install
        run: pnpm install
      - name: install browsers
        run: pnpm --filter @test/e2e exec playwright install --with-deps chromium
      - name: run e2e
        run: pnpm test:e2e
  teardown:
    needs: [unit, plugins, cfc, e2e]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
